[colors.bright]
black = "#000000"
blue = "#0000ff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.cursor]
cursor = "#ff0000"

[colors.dim]
black = "#131415"
blue = "#556a7d"
cyan = "#5b7d78"
green = "#777c44"
magenta = "#75617b"
red = "#864343"
white = "#828482"
yellow = "#9e824c"

[colors.normal]
black = "#000000"
blue = "#00ffff"
cyan = "#00ffff"
green = "#008000"
magenta = "#ff00ff"
red = "#800000"
white = "#ffffff"
yellow = "#ffff00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.selection]
background = "#00ffff"
text = "#000000"

[font]
size = 10.0

[window]
dynamic_title = true
opacity = 0.9
